Repository KhalisFoundation/sttm-desktop, pull requests merged in 2018-12, with the labels that each got.

#373 adds new toggle for presenter view
  www/index.html
  www/js/controller.js
  www/js/search.js
  www/src/scss/_footer.scss
Labels: 5.0, new feature

#372 Cmd +e / Ctrl + e shows empty slide
  www/js/index.js
Labels: 5.0

#370 Add Google analytics
  analytics.js
  app.js
  package-lock.json
  package.json
  www/js/banidb/constants.js
  www/js/controller.js
  www/js/defaults.json
  www/js/menu.js
  www/js/overlay.js
  www/js/search.js
  www/js/settings.js
  www/js/settings.json
  www/js/theme_editor.js
Labels: 5.0, enhancement

#376 Pressing a letter should go to that panktee in current shabad panel.
  www/index.html
  www/js/index.js
  www/js/search.js
  www/src/scss/styles.scss
Labels: 5.0

#371 adds asterisk as wild char for realm search
  www/js/banidb/realm-search.js
  www/js/banidb/sqlite-search.js
Labels: 5.0

#400 Bani overlay bg
  www/assets/img/maharaj.jpg
  www/src/scss/_overlay.scss
Labels: 5.0

#403 changes the focus pattern
  www/src/scss/styles.scss
Labels: 5.0

#401 chromecast bisram removal fixes #399
  www/js/viewer.js
Labels: 5.0

#390 Fix uploading a custom background images
  www/js/theme_editor.js
Labels: 5.0

#384 Update HELP.md for 5.0
  CHANGELOG.md
  HELP.md
Labels: 5.0
